In [1]:
# prompt: {
#   "nbformat": 4,
#   "nbformat_minor": 0,
#   "metadata": {
#     "colab": {
#       "provenance": []
#     },
#     "kernelspec": {
#       "name": "python3",
#       "display_name": "Python 3"
#     },
#     "language_info": {
#       "name": "python"
#     }
#   },
#   "cells": [
#     {
#       "cell_type": "code",
#       "execution_count": null,
#       "metadata": {
#         "id": "4EUY88PRyJQi"
#       },
#       "outputs": [],
#       "source": []
#     },
#     {
#       "cell_type": "code",
#       "execution_count": 1,
#       "metadata": {
#         "id": "u3SwNzHVw72g"
#       },
#       "outputs": [],
#       "source": [
#         "import numpy as np\n",
#         "import pandas as pd\n",
#         "import matplotlib.pyplot as plt\n",
#         "import seaborn as sns"
#       ]
#     },
#     {
#       "cell_type": "code",
#       "source": [
#         "links = pd.read_csv('/links.csv')"
#       ],
#       "metadata": {
#         "id": "xZTgOG9W0XTx"
#       },
#       "execution_count": 4,
#       "outputs": []
#     },
#     {
#       "cell_type": "code",
#       "source": [
#         "movies = pd.read_csv('/movies.csv')"
#       ],
#       "metadata": {
#         "id": "LGhxeOgu1D1d"
#       },
#       "execution_count": 5,
#       "outputs": []
#     },
#     {
#       "cell_type": "code",
#       "source": [
#         "ratings = pd.read_csv('/ratings.csv')"
#       ],
#       "metadata": {
#         "id": "3jSI_0rU1ESY"
#       },
#       "execution_count": 6,
#       "outputs": []
#     },
#     {
#       "cell_type": "code",
#       "source": [
#         "tags = pd.read_csv('/tags.csv')"
#       ],
#       "metadata": {
#         "id": "-ipXY9mP1Eh9"
#       },
#       "execution_count": 7,
#       "outputs": []
#     },
#     {
#       "cell_type": "markdown",
#       "source": [
#         "# Descrição geral do dataset"
#       ],
#       "metadata": {
#         "id": "g20nz8VUyok5"
#       }
#     },
#     {
#       "cell_type": "code",
#       "source": [
#         "links.info()"
#       ],
#       "metadata": {
#         "colab": {
#           "base_uri": "https://localhost:8080/"
#         },
#         "id": "umZEjf6R2H8O",

"outputId": "57549574-8691-41c9-8f72-69169089e206"
      },
      "execution_count": 8,
      "outputs": [
        {
          "output_type": "execute_result",
          "data": {
            "text/plain": [
              "<class 'pandas.core.frame.DataFrame'>\n",
              "RangeIndex: 9742 entries, 0 to 9741\n",
              "Data columns (total 3 columns):\n",
              " #   Column   Non-Null Count  Dtype  \n",
              "---  ------   --------------  -----  \n",
              " 0   movieId  9742 non-null   int64  \n",
              " 1   imdbId   9742 non-null   int64  \n",
              " 2   tmdbId   9734 non-null   float64\n",
              "dtypes: float64(1), int64(2)\n",
              "memory usage: 228.5 KB"
            ]
          },
          "metadata": {},
          "execution_count": 8
        }
      ]
    }
  ]
}

SyntaxError: unmatched '}' (<ipython-input-1-17c1fdfdde0d>, line 105)